language: shell

git:
  depth: 1

os:
  - osx
  - linux

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export PREFIX=MacOSX
      alias ldd='otool -L'
    else
      export PREFIX=Linux
    fi
    export FILES=`ls OpenMEEG*${PREFIX}.tar.gz`
    for f in $FILES; do
      tar -xvzf ${f};
      cd ${f/.tar.gz/};
      pwd;
      ls -lR;
      ldd ./bin/om_assemble;
      ldd ./lib/libOpenMEEGMaths.dylib;
      cd ..;
    done

  - ./bin/om_assemble
 
branches:
  only:
    - master

# trigger travis
