language: shell

os:
  - osx
  - linux

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      shopt -s expand_aliases;
      alias ldd='otool -L';
      tar -xvzf OpenMEEG*MacOSX.tar.gz;
      cd OpenMEEG*MacOSX
    else
      tar -xvzf OpenMEEG*Linux.tar.gz;
      cd OpenMEEG*Linux
    fi
  - pwd
  - ls -lR
  - ldd ./bin/om_xxx
  - ldd ./lib/libOpenMEEGMaths.so
  - ./bin/om_xxx
 
branches:
  only:
    - master

# trigger travis
