language: shell

git:
  depth: 1

os:
  - osx
  - linux

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      tar -xvzf OpenMEEG*MacOSX.tar.gz;
      cd OpenMEEG*MacOSX
      pwd
      ls -lR
      otool -L ./bin/om_assemble
      otool -L ./lib/libOpenMEEGMaths.dylib
    else
      tar -xvzf OpenMEEG*Linux.tar.gz;
      cd OpenMEEG*Linux
      pwd
      ls -lR
      ldd ./bin/om_assemble
      ldd ./lib/libOpenMEEGMaths.so
    fi
  - ./bin/om_assemble
 
branches:
  only:
    - master

# trigger travis
