language: shell

git:
  depth: 1

os:
  - osx
  - linux

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export PREFIX=MacOSX
      export LDD='otool -L'
    else
      export PREFIX=Linux
      export LDD='ldd'
    fi
    export FILES=`ls OpenMEEG*${PREFIX}.tar.gz`
    for f in $FILES; do
      tar -xvzf ${f};
      cd ${f/.tar.gz/};
      pwd;
      ls -l;
      $LDD ./bin/om_assemble;
      $LDD ./lib/libOpenMEEGMaths.dylib;
      cd ..;
    done
 
branches:
  only:
    - master

# trigger travis
